language: cpp

compiler:
    - clang

os:
    - osx

env:
    - CMAKE_BUILD_TYPE="Debug"
    - CMAKE_BUILD_TYPE="Release"

before_install:
    - brew outdated boost || brew upgrade boost
    - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git

before_script:
    - cd ejdb
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ../
    - make
    - make install
    - cd ../../

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ../
    - make

after_success:
    - make clean
    - touch ../include/meteorpp/*.hpp
    - make tests CXXFLAGS="-std=c++11 -fprofile-arcs -ftest-coverage"
    - cd ../
    - coveralls --exclude ejd --gcov-options '\-lp'
