language: cpp

matrix:
    include:
        - os: linux
          compiler: gcc
          env: CMAKE_BUILD_TYPE="Debug"
          before_install:
              - sudo apt-get install libboost-all-dev
              - sudo pip install cpp-coveralls
          after_success:
              - make tests
              - ./tests
              - cd ../
              - coveralls -i src/ -i include/meteorpp/ --gcov-options '\-lp'
        - os: osx
          compiler: clang
          env: CMAKE_BUILD_TYPE="Debug"
          before_install:
              - brew outdated boost || brew upgrade boost


before_script:
    - cd ejdb/
    - mkdir build
    - cd build/
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ../
    - make
    - sudo make install
    - cd ../../

script:
    - mkdir build
    - cd build/
    - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} ../
    - make
